### ISSUE TITLE
Feature Request: create .ini settings for key settings

### ISSUE THREAD

**Issue by bryanlatten** [php-memcached-dev/php-memcached#215]
From: https://github.com/php-memcached-dev/php-memcached/issues/187

Looking to configure memcached extension before runtime, for sanity
- hash_strategy 
- consistent hash
- protocol

Thanks!

**Comment by mkoppanen** [comment]
By hash strategy you mean the hashing algorithm? If I understand correctly these would be:

MEMCACHED_BEHAVIOR_HASH
MEMCACHED_BEHAVIOR_DISTRIBUTION
MEMCACHED_BEHAVIOR_BINARY_PROTOCOL

ref http://docs.libmemcached.org/memcached_behavior.html

**Comment by bryanlatten** [comment]
@mkoppanen those are them, correct. I was using the legacy `memcache` extension's naming, my apologies.

**Comment by sodabrew** [comment]
Are any code changes needed to satisfy this ticket?

**Comment by sodabrew** [comment]
Ok, I get what you're asking for now. In this extension these settings are configured in PHP code. There's no sense configuring the distribution algorithm in the INI file if the servers are configured from PHP space. It just doesn't align in a sensible way.

Because the hashing algorithms are incompatible between memcache.so and memcached.so, and because the serialization flags are different, you absolutely must not run the two extensions side-by-side in the same application cluster.

**Comment by bryanlatten** [comment]
@sodabrew not asking to run the extensions side by side, just using them as a comparison. Configured the extension from PHP space leaves the task to the app(s), which i'd rather enforce (once) in infrastructure. Does that make sense?

**Comment by sodabrew** [comment]
If these are configured in the INI file, should they become immutable by application code? Should there also be a server list that is configurable in the INI file?

**Comment by bryanlatten** [comment]
Overall, the server list is dynamic, but the connection settings should likely not be (right?). 
Best case scenario would have ini settings applied first, and overridable at runtime - if necessary.
