### ISSUE TITLE
Update PHP.net documentation

### ISSUE THREAD

**Issue by DomBlack** [php-memcached-dev/php-memcached#343]
The PHP.net documentation is out of date against the current API.

For example; http://php.net/manual/en/memcached.get.php doesn't mention the new way of getting CAS tokens.

**Comment by martin-georgiev** [comment]
I've just submitted a patch on edit.php.net for the Memcached PHP documentation, reflecting the API changes in `get`, `getByKey`, `getMulti` and `getMultiByKey`.
This should be reviewed soon.

**Comment by sodabrew** [comment]
Thanks @martin-georgiev! Hope that the changes are accepted to the documentation site soon.

**Comment by martin-georgiev** [comment]
The php.net documentation is now updated.
The updated pages are:
[Constants](http://php.net/manual/en/memcached.constants.php)
[Memcached::get](http://php.net/manual/en/memcached.get.php)
[Memcached::getByKey](http://php.net/manual/en/memcached.getbykey.php)
[Memcached::getMulti](http://php.net/manual/en/memcached.getmulti.php)
[Memcached::getMultiByKey](http://php.net/manual/en/memcached.getmultibykey.php)

Let me know of anything missing. Otherwise, I believe this issue can be closed.
